export const ADD_SERVICE = 'ADD_SERVICE';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const EDIT_SERVICE = 'EDIT_SERVICE'
export const CLEAN_CURRENT_SERVICE = 'CLEAN_CURRENT_SERVICE'
export const UPDATE_SERVICE = 'UPDATE_SERVICE'
export const FILTER_SERVICE = 'FILTER_SERVICE'